platform :ios, '8.0'
source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'Fishionary' do
    pod 'CHTCollectionViewWaterfallLayout'
    pod 'DownPicker'
    #pod 'RxSwift'
    #pod 'RxCocoa'
    pod 'GRMustache', '~> 7.3.2'
end
